language: cpp

dist: xenial
sudo: false

matrix:
  include:
    - env: LABEL="Linux module" GDNATIVE=no
      os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - &linux_module_deps [libasound2-dev, libgl1-mesa-dev, libglu1-mesa-dev, libx11-dev, libxcursor-dev, libxi-dev, libxinerama-dev, libxrandr-dev]

    - env: LABEL="Linux GDNative" GDNATIVE=yes
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - xenial-backports
          packages:
            - &linux_gdn_deps [meson, ninja-build]

install:
  - pip install --user scons;

script:
  - if [ "$GDNATIVE" = "yes" ]; then
      cd godot-cpp;
      scons -j2 platform=linux bits=64 target=debug generate_bindings=yes use_custom_api_file=yes custom_api_file="../api_3_1.json";
      cd ..;
      meson ./_build_linux64 -Dgodot-cpp-lib-name=libgodot-cpp.linux.debug.64 -Dbuiltin-runtime=true -Duse-graphite2=true;
      ninja -C ./_build_linux64;
    else
      git clone --depth 1 https://github.com/godotengine/godot _build_module;
      cd _build_module;
      ln -s .. ./modules/godot_tl;
      scons -j2 platform=x11 bits=64 target=debug tools=yes warnings=extra module_hdr_enabled=no module_bmp_enabled=no module_bullet_enabled=no module_jpg_enabled=no module_squish_enabled=no module_csg_enabled=no module_stb_vorbis_enabled=no module_cvtt_enabled=no module_mbedtls_enabled=no module_dds_enabled=no module_tga_enabled=no module_enet_enabled=no module_thekla_unwrap_enabled=no module_etc_enabled=no module_mobile_vr_enabled=no module_theora_enabled=no module_ogg_enabled=no module_upnp_enabled=no module_gdnative_enabled=no module_opensimplex_enabled=no module_opus_enabled=no module_vorbis_enabled=no module_pvr_enabled=no module_webm_enabled=no module_recast_enabled=no module_webp_enabled=no module_websocket_enabled=no module_gridmap_enabled=no module_xatlas_unwrap_enabled=no builtin_freetype=yes builtin_libpng=yes builtin_zlib=yes;
    fi
