language: cpp

dist: bionic

stages:
  - check
  - build

branches:
  only:
    - master

matrix:
  include:
    - name: Static checks (clang-format)
      stage: check
      env: STATIC_CHECKS=yes
      os: linux
      compiler: gcc
      addons:
        apt:
          packages:
            - clang-format-8

    - name: Linux module (Tools, Debug, 3.2.2-dev)
      stage: build
      env: GDNATIVE=no GDVER=32
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - sourceline: "ppa:ubuntu-toolchain-r/test"
          packages:
            - &linux_deps [libasound2-dev, libgl1-mesa-dev, libglu1-mesa-dev, libx11-dev, libxcursor-dev, libxi-dev, libxinerama-dev, libxrandr-dev]

    - name: Linux module (Tools, Debug, 3.2.1-stable)
      stage: build
      env: GDNATIVE=no GDVER=31
      os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - *linux_deps

    - name: Linux module (Export Template, Release, 3.2.2-dev)"
      stage: build
      env: GDNATIVE=no GDVER=32e
      os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - *linux_deps

    - name: Linux module (Export Template, Release, 3.2.1-stable)
      stage: build
      env: GDNATIVE=no GDVER=31e
      os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - *linux_deps

    - name: Linux GDNative
      stage: build
      env: GDNATIVE=yes
      os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
          packages:
            - meson
            - ninja-build
            - *linux_deps

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      pyenv global 3.8 system;
      pip3 install --user scons;
    fi
  - scons --version

script:
  - if [ "$STATIC_CHECKS" = "yes" ]; then
      bash ./.scripts/clang_format.sh;
    elif [ "$GDNATIVE" = "yes" ]; then
      bash ./.scripts/gdn_build.sh;
    elif [ "$GDVER" = "32" ]; then
      bash ./.scripts/module_build_3_2_2.sh;
    elif [ "$GDVER" = "31" ]; then
      bash ./.scripts/module_build_3_2_1.sh;
    elif [ "$GDVER" = "32e" ]; then
      bash ./.scripts/module_build_3_2_2_export.sh;
    elif [ "$GDVER" = "31e" ]; then
      bash ./.scripts/module_build_3_2_1_export.sh;
    fi
